version: '3.6'
services:

  www:
    container_name: babylon_www
    build:
      context: ../www
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ../www:/usr/src/app

  server:
    container_name: babylon_server
    build:
      context: ../server
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ../server:/usr/src/app
    links:
      - db

  db:
    container_name: mongo_db
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  mongo-data:
